version: '3'

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3013:3013'
            - '4014:4014'
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - .env

    db:
        image: mongo
        command: ['--quiet', '--logpath', '/dev/null']
        ports:
            - '27017:27017'
        env_file:
            - .env
