import { ITEM_CONSUMABLE_1, ITEM_MATERIAL_1, ITEM_WEAPON_1 } from '../../items/items/items';
import { CharacterClass } from '../../.shared/types';
import { Enemy } from '../types';

export const ENEMY_1: Enemy = {
    uid: 'enemy-1-1',
    name: 'Green Goblin',
    level: 1,
    class: CharacterClass.Warrior,
    baseStatistics: {
        health: 100,
        mana: 0,
        physicalDef: 10,
        physicalAtk: 10,
        speed: 20,
        criticalChance: 0.1,
        criticalPower: 1.5,
    },
    potential: {
        health: 10,
        mana: 0,
        physicalDef: 0.5,
        physicalAtk: 0.5,
        speed: 1,
        criticalChance: 0,
        criticalPower: 0,
    },
    moves: [{ uid: 'move-01', name: 'Small Bash', damage: 10 }],
    loots: [{ itemUid: ITEM_MATERIAL_1.uid, itemName: ITEM_MATERIAL_1.name, chance: 0.3 }],
    experience: 20,
    gold: 3,
};

export const ENEMY_2: Enemy = {
    uid: 'enemy-1-2',
    name: 'Tall Ogre',
    level: 1,
    class: CharacterClass.Warrior,
    baseStatistics: {
        health: 200,
        mana: 0,
        physicalDef: 0,
        physicalAtk: 20,
        speed: 10,
        criticalChance: 0.1,
        criticalPower: 1.5,
    },
    potential: {
        health: 15,
        mana: 0,
        physicalDef: 0.5,
        physicalAtk: 0.5,
        speed: 1,
        criticalChance: 0,
        criticalPower: 0,
    },
    moves: [{ uid: 'move-02', name: 'Slow Slash', damage: 20 }],
    loots: [{ itemUid: ITEM_MATERIAL_1.uid, itemName: ITEM_MATERIAL_1.name, chance: 0.4 }],
    experience: 30,
    gold: 5,
};

export const ENEMY_3: Enemy = {
    uid: 'enemy-1-3',
    name: 'Cave Troll',
    level: 1,
    class: CharacterClass.Warrior,
    baseStatistics: {
        health: 180,
        mana: 0,
        physicalDef: 10,
        physicalAtk: 20,
        speed: 20,
        criticalChance: 0.1,
        criticalPower: 1.5,
    },
    potential: {
        health: 15,
        mana: 0,
        physicalDef: 1,
        physicalAtk: 1.5,
        speed: 1.5,
        criticalChance: 0,
        criticalPower: 0,
    },
    moves: [{ uid: 'move-03', name: 'Mellow Pierce', damage: 15 }],
    loots: [{ itemUid: ITEM_MATERIAL_1.uid, itemName: ITEM_MATERIAL_1.name, chance: 0.4 }],
    experience: 30,
    gold: 5,
};

export const ENEMY_4: Enemy = {
    uid: 'enemy-1-4',
    name: 'Errant Knight',
    level: 1,
    class: CharacterClass.Warrior,
    baseStatistics: {
        health: 500,
        mana: 150,
        physicalDef: 20,
        physicalAtk: 30,
        speed: 20,
        criticalChance: 0.2,
        criticalPower: 1.75,
    },
    potential: {
        health: 50,
        mana: 0,
        physicalDef: 2,
        physicalAtk: 3,
        speed: 2,
        criticalChance: 0,
        criticalPower: 0,
    },
    moves: [{ uid: 'move-04', name: 'Carpe Diem', damage: 200 }],
    loots: [{ itemUid: ITEM_WEAPON_1.uid, itemName: ITEM_WEAPON_1.name, chance: 0.1 }],
    experience: 100,
    gold: 25,
};

export const ENEMY_5: Enemy = {
    uid: 'enemy-1-5',
    name: 'Agile Goblin',
    level: 3,
    class: CharacterClass.Hunter,
    baseStatistics: {
        health: 125,
        mana: 0,
        physicalDef: 10,
        physicalAtk: 15,
        speed: 25,
        criticalChance: 0.2,
        criticalPower: 1.5,
    },
    potential: {
        health: 10,
        mana: 0,
        physicalDef: 0.5,
        physicalAtk: 0.5,
        speed: 1,
        criticalChance: 0,
        criticalPower: 0,
    },
    moves: [{ uid: 'move-01', name: 'Small Bash', damage: 15 }],
    loots: [{ itemUid: ITEM_MATERIAL_1.uid, itemName: ITEM_MATERIAL_1.name, chance: 0.3 }],
    experience: 20,
    gold: 4,
};

export const ENEMY_6: Enemy = {
    uid: 'enemy-1-6',
    name: 'Young Griffin',
    level: 3,
    class: CharacterClass.Warrior,
    baseStatistics: {
        health: 400,
        mana: 0,
        physicalDef: 20,
        physicalAtk: 40,
        speed: 40,
        criticalChance: 0.2,
        criticalPower: 1.5,
    },
    potential: {
        health: 40,
        mana: 0,
        physicalDef: 2,
        physicalAtk: 4,
        speed: 4,
        criticalChance: 0,
        criticalPower: 0,
    },
    moves: [{ uid: 'move-01', name: 'Brave Bird', damage: 50 }],
    loots: [{ itemUid: ITEM_MATERIAL_1.uid, itemName: ITEM_MATERIAL_1.name, chance: 0.5 }],
    experience: 60,
    gold: 20,
};

export const ENEMY_7: Enemy = {
    uid: 'enemy-1-7',
    name: 'Bronze Construct',
    level: 5,
    class: CharacterClass.Warrior,
    baseStatistics: {
        health: 400,
        mana: 100,
        physicalDef: 30,
        physicalAtk: 30,
        speed: 10,
        criticalChance: 0.1,
        criticalPower: 1.5,
    },
    potential: {
        health: 40,
        mana: 0,
        physicalDef: 30,
        physicalAtk: 30,
        speed: 10,
        criticalChance: 0,
        criticalPower: 0,
    },
    moves: [{ uid: 'move-01', name: 'Spiral Slash', damage: 30 }],
    loots: [],
    experience: 50,
    gold: 10,
};

export const ENEMY_X_1: Enemy = {
    uid: 'enemy-x-1',
    name: 'Deus Cras',
    level: 5,
    class: CharacterClass.Wizzard,
    baseStatistics: {
        health: 2500,
        mana: 250,
        physicalDef: 25,
        physicalAtk: 25,
        speed: 25,
        criticalChance: 0.25,
        criticalPower: 1.75,
    },
    potential: {
        health: 250,
        mana: 25,
        physicalDef: 2.5,
        physicalAtk: 2.5,
        speed: 2.5,
        criticalChance: 0,
        criticalPower: 0,
    },
    moves: [{ uid: 'move-01', name: 'Daybreak', damage: 150 }],
    loots: [{ itemUid: ITEM_CONSUMABLE_1.uid, itemName: ITEM_CONSUMABLE_1.name, chance: 1 }],
    experience: 1000,
    gold: 100,
};
