@base_url = https://94c0s06hze.execute-api.eu-central-1.amazonaws.com/prod
@test_login = test
@test_password = specAA11#

GET {{base_url}}/spaces

###

POST {{base_url}}/spaces
content-type: application/json

{
    "location": "Stockholm",
    "name": "stock-1"
}

###

PUT {{base_url}}/spaces?id=ea7a4f66-a42d-4bfb-a9dd-839e9976a993
content-type: application/json

{
    "location": "Kazimierz"
}

###

DELETE {{base_url}}/spaces?id=ea7a4f66-a42d-4bfb-a9dd-839e9976a993
content-type: application/json
