/* tslint:disable */
/* eslint-disable */
/**
 * express-blueprint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadById200Response
 */
export interface ReadById200Response {
    /**
     * 
     * @type {number}
     * @memberof ReadById200Response
     */
    level: number;
    /**
     * 
     * @type {string}
     * @memberof ReadById200Response
     */
    login: string;
    /**
     * 
     * @type {any}
     * @memberof ReadById200Response
     */
    id: any | null;
}

/**
 * Check if a given object implements the ReadById200Response interface.
 */
export function instanceOfReadById200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "level" in value;
    isInstance = isInstance && "login" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function ReadById200ResponseFromJSON(json: any): ReadById200Response {
    return ReadById200ResponseFromJSONTyped(json, false);
}

export function ReadById200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadById200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'level': json['level'],
        'login': json['login'],
        'id': json['id'],
    };
}

export function ReadById200ResponseToJSON(value?: ReadById200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'level': value.level,
        'login': value.login,
        'id': value.id,
    };
}

