/* tslint:disable */
/* eslint-disable */
/**
 * express-blueprint
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCreateDto
 */
export interface UserCreateDto {
    /**
     * 
     * @type {string}
     * @memberof UserCreateDto
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreateDto
     */
    login: string;
}

/**
 * Check if a given object implements the UserCreateDto interface.
 */
export function instanceOfUserCreateDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "password" in value;
    isInstance = isInstance && "login" in value;

    return isInstance;
}

export function UserCreateDtoFromJSON(json: any): UserCreateDto {
    return UserCreateDtoFromJSONTyped(json, false);
}

export function UserCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': json['password'],
        'login': json['login'],
    };
}

export function UserCreateDtoToJSON(value?: UserCreateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
        'login': value.login,
    };
}

